### ISSUE TITLE
Blocked repos keep getting scheduled

### ISSUE THREAD

**Issue by wei** [probot/scheduler#25]
Background: A user has ~650 repos, out of which 2 forks are blocked because the parent repo is blocked.

Problem Description:
I found that the (DMCA or ToS) blocked repos don’t appear blocked when fetched using getInstallationRepositories. So filters wouldn’t really work. 

Ideally probot-scheduler should just stop scheduling those repos. 
 * Method 1. Ask Github to include some indication that repo is blocked so probot-scheduler can just skip it. (Con: Probably won't happen)
 * Method 2. Run a get repo call for each repo before scheduling. (Con: Overhead)

My temporary solution: Since I am using `probot-config`, I catch the error there and unschedule the repos.

**Comment by dibyendu** [comment]
Not only blocked repos, deleted repos are also getting scheduled even after the app is uninstalled.

This is because only the `installation.created` and `installation_repositories.added` events are being handled:
https://github.com/probot/scheduler/blob/ac82ab60706094427b2559d8d1f9f96a60d51925/index.js#L16
https://github.com/probot/scheduler/blob/ac82ab60706094427b2559d8d1f9f96a60d51925/index.js#L25

There is no handler for `installation_repositories.removed` and/or `installation.deleted`.

**Comment by jleach** [comment]
There is a `repository.deleted` event. I monitor it and just run `    scheduler.stop(context.payload.repository);` Seemed to be working ok - although I will go back and test it more.
