### ISSUE TITLE
Cannot read property 'merge' of undefined

### ISSUE THREAD

**Issue by cchantep** [probot/scheduler#35]
With following dependencies:

```json
{
    "probot": "^7.2.0",
    "probot-scheduler": "^2.0.0-beta.1",
}
```

Get:

```
11:49:10.467Z ERROR probot: Cannot read property 'merge' of undefined
  TypeError: Cannot read property 'merge' of undefined
      at eachInstallation (/Users/cchantep/Projects/pr-jira/node_modules/probot-scheduler/index.js:83:46)
      at <anonymous>
```

**Comment by cmcnamara87** [comment]
having the same problem

**Comment by linsolas** [comment]
Hello,

I have the same error.
I think the problem is [here](https://github.com/probot/scheduler/blob/master/index.js#L79-L81):

```js
    const installations = await github.paginate(
      github.apps.listInstallations.endpoint.merge({ per_page: 100 })
    )
```

as per the new Probot API, it should be more something like this:

```js
    const installations = await github.apps.listInstallations({ per_page: 100 })
```
(not exactly that, since we should work on the `installations.data`)

Of course, this should be done on others parts of the `probot-scheduler` (like [here](https://github.com/probot/scheduler/blob/master/index.js#L94)).

**Comment by linsolas** [comment]
Hello,

For information, I've made the PR #39 to solve this issue.

**Comment by moltenice** [comment]
It's still relevant, and is what's keeping me from using the beta

**Comment by moltenice** [comment]
Yes
